### ISSUE TITLE
I can not install on Laravel 9 !

### ISSUE THREAD

**Issue by yaser2490** [bpuig/laravel-subby#118]
Problem 1
    - bpuig/laravel-subby[v5.0.0, ..., v5.x-dev] require laravel/framework ^6.0|^7.0|^8.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0
.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - bpuig/laravel-subby v5.0.2 requires laravel/framework ^v8.38.0 -> found laravel/framework[v8.38.0, ..., 8.x-dev] but it conflicts with yo
ur root composer.json require (^9.0).
    - Root composer.json requires bpuig/laravel-subby ^5.0 -> satisfiable by bpuig/laravel-subby[v5.0.0, v5.0.1, v5.0.2, v5.x-dev].

**Comment by bpuig** [comment]
Hello, at the moment I am working on the new `v6` that will support Laravel 9 and add new features. You can take a look at the `dev` version, but I do not recommend to use it in production, since it is not finished yet. Just start reading the docs to get familiar and soon this new version will be released.

**Comment by aeq-dev** [comment]
Any update on this ? thanks

**Comment by bpuig** [comment]
Version 6 is compatible with laravel 9 🙃
