### ISSUE TITLE
Doubts starting using this

### ISSUE THREAD

**Issue by rikardow** [bpuig/laravel-subby#151]
Hi, first of all, thanks for this great project, but I'm having some doubts configuring this, where I'm supposed to put the Plans/Features definition? On a migration or on a model? Thanks

**Comment by bpuig** [comment]
Do you mean feeding the data?
Or defining the relationship? 
Can you explain further?
Thanks

**Comment by rikardow** [comment]
This part, when you create a plan:

![image](https://user-images.githubusercontent.com/38504051/219475055-8d4fc793-e72f-4e63-942a-7d56bfdfeeb8.png)

Seems like something to put on a migration to create the plan once, but I'm not really sure if that's how it's intended to work

Same question with the Plan Features: 

![image](https://user-images.githubusercontent.com/38504051/219474974-044694b9-a63a-4050-9a12-689c997e597f.png)

Thanks for your help

**Comment by bpuig** [comment]
I can give my opinion, but the last word on how to make it depends on you and the needs of your project. This examples are filled with written text for explaining purposes, if your data is not static I'm sure you will need to make your CRUD endpoints to maintain the plans.

If it is something you do not plan to ever change, you can use a Seeder or Migration. But this doubt is more about best practices and how you have structured your project than something that needs to be clarified in the package.

The decision is yours, because only you know the needs of your app.

**Comment by rikardow** [comment]
I'm just gonna take a look at the source code to see how exactly this works so I can choose the best way, thanks for your help
