### ISSUE TITLE
Call to a member function getFeatureUsage() on null

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#28]
The could be some gracefull handling if we refer to an non-existing subscription tag. 

When I call `$usage = $user->subscription('primary')->getFeatureUsage('social_profiles');` and there is no 'primary' subscription, I get 'Call to a member function getFeatureUsage() on null'. I think it would be better just to return `null`, as this user does not the subscription 'primary' so that he does not have the feature either.

The same goes for `getFeatureRemainings()`, etc.

**Comment by bpuig** [comment]
Would not be better to just throw an exception "subscription does not exist" or similar?
Because returning null might get you thinking subscription exists and starting one of that circles where you do not know what is not working and end up finding you were pointing the wrong subscription all the time and end up like: 🤦‍♂️

Also I'm writing this without looking at the code. Let me see it today and fix one way or another before release.

**Comment by boryn** [comment]
Yes, I was thinking about the exception as well. If properly used by a developer, would be a better solution :) And it would be on the part of developer to handle it properly. 

It would be worth mentioning in the docs that it's recommendable to wrap `$user->subscription('primary')->getFeatureUsage('social_profiles');` in the try/catch block.

**Comment by bpuig** [comment]
Solved in e3d2f336b1c2ffa1331e2a9c195f5ca5b3970e64
