### ISSUE TITLE
What is a 'tier'?

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#34]
Actually how the `tier` should be used? I have not found any information about it in the docs

**Comment by bpuig** [comment]
Usually a `tier` is a "level" of subscription. It helps with _upgrading_ or _downgrading_ because usually an _upgrade_ is changed, billed an renewed instantly and a _downgrade_ is changed and billed at the end of period (that's why schedule package exists).

The way it's thought is, ex: 

You have 3 plans: **Basic**, **Intermediate** and **Pro**. How do you now which is better than the other? You can look at the price.

But... what if there is a promo during some time and the price of **Intermediate** is lower now than **Basic** will be next month when there is no promo? When you change the subscription plan from your promo **Intermediate** to **Basic** normally would be a _downgrade_, but now prices are reversed and action is an _upgrade_. Weird, huh?

What if you customize your user subscription and now its somewhere in the middle between **Intermediate** and **Pro**? You can change the tier to a number in between so you know what to do when changing (_downgrading_) to existing **Intermediate** or _upgrading_ to **Pro**.

**Comment by bpuig** [comment]
Written explanation in 1c76419
